### ISSUE TITLE
Form data returns as unfiltered string objects

### ISSUE THREAD

**Issue by RocktimSaikia** [talentlessguy/parsec#4]
This is the current behavior. If you try to access the form data with the `form` property of `parsec` It returns an unfiltered String.

![Screenshot_3](https://user-images.githubusercontent.com/33410545/91658199-c3676e00-eae4-11ea-94ce-cc392d79b388.png)

**Comment by talentlessguy** [comment]
I need to rename the method with `parsec.urlencoded` lol

**Comment by talentlessguy** [comment]
Done in 2.1.0
